### ISSUE TITLE
导出的settings里没有换行

### ISSUE THREAD

**Issue by yingsotu** [kaluluosi/GDExcelExporter#14]
![image](https://user-images.githubusercontent.com/7201730/228705933-ceb1cd5d-f0ee-46d0-a445-df6d74605468.png)

**Comment by yingsotu** [comment]
![image](https://user-images.githubusercontent.com/7201730/228706851-ccebd76f-b463-4fd6-a7c6-d6d30167c93b.png)
加了\n之后正常了

**Comment by kaluluosi** [comment]
是个bug 等下修复
