### ISSUE TITLE
一点关于易用性的提议

### ISSUE THREAD

**Issue by eterlan** [kaluluosi/GDExcelExporter#24]
1. 在编辑器内运行脚本
```gdscript
@tool
extends EditorScript

# Called when the script is executed (using File -> Run in Script Editor).
func _run() -> void:
	var output = []
	var 
	OS.execute("CMD.exe", ["/c", "D:\\Godot\\Projects\\Ranger\\db\\gen_all.bat"], output)
	print(output)
```
bat文件要加上 cd db

2. 根据表格生成类文件会不会更好用一些，这样能用auto complete和类型检查

**Comment by kaluluosi** [comment]
关于问题1，你可以试试我以前写的GD小插件：
https://github.com/kaluluosi/GDEexcelExporer-Plugin

**Comment by kaluluosi** [comment]
@eterlan https://github.com/kaluluosi/GDEexcelExporer-Plugin 有更新，之前不支持Godot4.0，现在迭代了下支持4.0了，而且增加了个一键导出按钮。

**Comment by eterlan** [comment]
> @eterlan https://github.com/kaluluosi/GDEexcelExporer-Plugin 有更新，之前不支持Godot4.0，现在迭代了下支持4.0了，而且增加了个一键导出按钮。

大佬辛苦了。话说大佬有没有交流群啥的 🤣
