### ISSUE TITLE
跪求大佬增加Mac的支持

### ISSUE THREAD

**Issue by yingsotu** [kaluluosi/GDExcelExporter#30]
台式机用的Windows，笔记本用的Mac，迫切需要支持Mac。

**Comment by kaluluosi** [comment]
![image](https://github.com/kaluluosi/GDExcelExporter/assets/1620585/9644abc2-ee4d-4ca6-8eab-f91833f3039e)

xlwings 目前不支持mac。 只能之后我再加一个 openpyxl的读写接口。

**Comment by kaluluosi** [comment]
- [ ] 重构Engine框架，提供xlrd（默认），xlwings两种引擎。xlrd支持全平台，而且速度更快。
- [ ] 增加配置文件自动升级修复功能来帮助用户更新最新的toml配置
- [ ] toml配置增加engine字段的说明
