### ISSUE TITLE
请问作者会考虑之后增加枚举类型吗？

### ISSUE THREAD

**Issue by JourneyHans** [kaluluosi/GDExcelExporter#32]
配置“类型”相关的字段时，若果类型太多，用int还是不太方便。

**Comment by kaluluosi** [comment]
你得给个大概的想法给我。你希望我怎么导出枚举。
比如是不是用一个sheet来定义枚举，然后将其每个sheet对应一个enum 导出到enum.gd？或者导出到settings.gd里？
你可以自己拟定一个方案贴上来，我好参考。
