### ISSUE TITLE
2.1.5版本中，Office Excel作为启动方法时会导致一键导表报错

### ISSUE THREAD

**Issue by guanglin-chef** [kaluluosi/GDExcelExporter#45]
<img width="1073" alt="无标题" src="https://github.com/kaluluosi/GDExcelExporter/assets/39788228/b4e9bcb1-3091-45bf-af9b-f0d1a019f2df">

如图所示
在上图这个报错后用Office打开文件会提示：
![QQ图片20240526132937](https://github.com/kaluluosi/GDExcelExporter/assets/39788228/550d77f4-786e-4b0f-a148-1e08638e2dc1)
并且会有概率一口气打开之前在一键导表中打开失败的若干个表

之前一直使用都没有问题，疑似是最近windows更新后office的一些额外的弹窗导致的问题

**Comment by kaluluosi** [comment]
升级一下包吧，3.x版本 已经修改为使用xlrd来读取excel了，同时兼容mac linux windows 三个平台的导出。
不过由于对类型定义做了调整，需要修改一下。详情可以看README和在线文档。
> pip install -U gd_excelexporter

**Comment by guanglin-chef** [comment]
好的，不过现在3.x版本似乎没有无需python环境的ee.exe。
目前工作室里很多人还是很需要这个的……希望大佬能提供一个
